/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: 'rgb(var(--bg) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--surface-3) / <alpha-value>)',
        field: 'rgb(var(--field) / <alpha-value>)',
        'field-hover': 'rgb(var(--field-hover) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-2': 'rgb(var(--border-2) / <alpha-value>)',
        'border-3': 'rgb(var(--border-3) / <alpha-value>)',
        track: 'rgb(var(--track) / <alpha-value>)',
        ink: 'rgb(var(--ink) / <alpha-value>)',
        text: 'rgb(var(--text) / <alpha-value>)',
        'text-2': 'rgb(var(--text-2) / <alpha-value>)',
        label: 'rgb(var(--label) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        'muted-2': 'rgb(var(--muted-2) / <alpha-value>)',
        soft: 'rgb(var(--soft) / <alpha-value>)',
        sidebar: 'rgb(var(--sidebar) / <alpha-value>)',
        panel: 'rgb(var(--panel) / <alpha-value>)',
        brand: 'rgb(var(--brand) / <alpha-value>)',
        'brand-hover': 'rgb(var(--brand-hover) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--accent-hover) / <alpha-value>)',
        disabled: 'rgb(var(--disabled) / <alpha-value>)',
        ok: 'rgb(var(--ok) / <alpha-value>)',
        warn: 'rgb(var(--warn) / <alpha-value>)',
        bad: 'rgb(var(--bad) / <alpha-value>)',
        'vac-bd': 'rgb(var(--vac-bd) / <alpha-value>)',
        'occ-bg': 'var(--occ-bg)', 'occ-bd': 'var(--occ-bd)',
        'pend-bg': 'var(--pend-bg)', 'pend-bd': 'var(--pend-bd)',
        'maint-bg': 'var(--maint-bg)', 'maint-bd': 'var(--maint-bd)',
        'vac-bg': 'var(--vac-bg)', 'bad-bg': 'var(--bad-bg)',
        'due-bg': 'var(--due-bg)', overlay: 'var(--overlay)',
        topbar: 'var(--topbar)',
        veg: 'rgb(var(--veg) / <alpha-value>)',
        nonveg: 'rgb(var(--nonveg) / <alpha-value>)',
        'ground-a': 'rgb(var(--ground-a) / <alpha-value>)',
        'ground-b': 'rgb(var(--ground-b) / <alpha-value>)',
        'st-vac': 'rgb(var(--st-vac) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['IBMPlexSans_400Regular'],
        'sans-medium': ['IBMPlexSans_500Medium'],
        'sans-semibold': ['IBMPlexSans_600SemiBold'],
        'sans-bold': ['IBMPlexSans_700Bold'],
        serif: ['IBMPlexSerif_600SemiBold'],
        'serif-bold': ['IBMPlexSerif_700Bold'],
        mono: ['IBMPlexMono_400Regular'],
        'mono-medium': ['IBMPlexMono_500Medium'],
        'mono-semibold': ['IBMPlexMono_600SemiBold'],
      },
    },
  },
  plugins: [],
};
